services:
  backend:
    build: 
      context: ./backend
      dockerfile: ../Dockerfile
    volumes:
      - ./coverage:/app/backend/coverage
    command: >
      sh -c "coverage run -m pytest tests/ && coverage report -m && coverage html"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    depends_on:
#      - backend
#    command: ["npm", "test", "-", "--watchAll=false"]
