services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /main
    volumes:
      - ./backend/reports:/main/backend/reports
      - ./backend/htmlcov:/main/backend/htmlcov
    command: >
      sh -c "coverage run -m --source=backend pytest --html=/main/backend/reports/test_report.html backend/tests/ || true && coverage report -m && coverage html -d /main/backend/htmlcov"