services:
  backend:
    build: backend
    command: python3 -u ./backend/run.py
    ports:
      - "4040:4040"
    volumes:
      - .:/main
      - ./backend/sqlite-data:/main/backend/sqlite-data

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  sqlite-data:

