services:
  backend:
    build: backend
    command: python3 -u ./backend/main.py
    ports:
      - "4040:4040"
    volumes:
      - .:/main
      - ./backend/sqlite-data:/main/backend/sqlite-data

volumes:
  sqlite-data:

