services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/htmlcov:/main/htmlcov
    command: >
      sh -c "coverage run -m --source=. pytest tests/ || true && coverage report -m && coverage html"

