services:
  backend:
    build: backend
    command: python -u ./backend/main.py
    ports:
      - "4040:4040"
    volumes:
      - .:/main
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=coursework_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
  whisper:
    image: whisper_timestamped_cpu:latest
    ports:
      - "5000:5000"
