services:
  backend:
    build: backend
    command: python3 -m backend
    ports:
      - "4040:4040"
    volumes:
      - .:/main
      - ./backend/sqlite-data:/main/backend/sqlite-data

  frontend:
    build: frontend
    command: npm run preview
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app/src
      - /app/node_modules

volumes:
  sqlite-data:

